name: bestcannedfood_ecommerce
description: A new Flutter project.

version: 1.1.4+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.0.0
  dotted_border: ^2.0.0
  flutter_swiper_null_safety: ^1.0.2
  settings_ui: ^0.6.0
  date_field: ^2.0.1
  heroicons: ^0.2.1
  intl: ^0.17.0
  rflutter_alert: ^1.0.3
  flutter_html: ^2.1.0
  smooth_star_rating_nsafe: ^1.0.0+1
  flutter_map: ^0.13.1
  url_launcher: ^6.0.9
  flutter_map_marker_popup: ^1.0.0+2
  flutter_advanced_drawer: ^1.2.3
  flutter_svg: any
  shimmer: ^2.0.0
  dotted_line: ^3.0.0
  lottie: ^1.1.0
  timeline_tile: ^2.0.0
  flutter_launcher_icons: ^0.9.1
  badges: ^2.0.1
  flutter_multi_formatter: ^2.3.2
  group_button: ^3.1.0
  group_radio_button: ^1.1.0
  photo_view: ^0.12.0
  youtube_player_flutter: ^8.0.0
  youtube_player_iframe: ^2.2.2
  bloc: ^7.2.1
  flutter_bloc: ^7.3.3
  rxdart: ^0.27.1
  dio: ^4.0.0
  equatable: ^2.0.3
  shared_preferences: ^2.0.6
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter_facebook_auth: ^3.5.0
  flutter_easyloading: ^3.0.0
  clipboard: ^0.1.3
  modal_bottom_sheet: ^2.0.0
  ticket_pass_package: ^0.1.0
  social_share: ^2.2.1
  cross_connectivity: ^3.0.2
  sms_autofill: ^2.2.0
  sms_receiver: ^0.4.0
  otp_autofill: ^2.0.0
  pin_input_text_field: ^4.1.1
  easy_localization: ^3.0.0
  syncfusion_flutter_sliders: ^19.3.54
  dropdown_search: ^2.0.1
  sign_in_with_apple: ^3.3.0
  image_picker: ^0.8.4+4
  flutter_local_notifications: ^9.1.4
  device_info: ^2.0.3
  cached_network_image: ^3.2.0
  lazy_load_scrollview: 1.3.0

dev_dependencies:
  flutter_test:      
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/translations/

  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/pyidaungsu.ttf